# Generated by Django 4.2.17 on 2025-01-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.IntegerField(choices=[(0, 'Save as Draft'),
                                               (1, 'Post')], default=0),
        ),
    ]
