# Generated by Django 4.2.17 on 2025-01-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horde', '0002_alter_book_review_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_on']},
        ),
    ]
