# Generated by Django 4.2.17 on 2025-01-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horde', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
